// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIK96UjKSiHL9tQZRBrHSaS_4d_SgmBSA',
    appId: '1:388247623060:web:563ea1570b11c2a62aab81',
    messagingSenderId: '388247623060',
    projectId: 'fir-fluter-codelab-4fc8c',
    authDomain: 'fir-fluter-codelab-4fc8c.firebaseapp.com',
    storageBucket: 'fir-fluter-codelab-4fc8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8YU2-4bdw76dWKOIGkvGC6h4ERR8RkXQ',
    appId: '1:388247623060:android:fb2a3417ca84650a2aab81',
    messagingSenderId: '388247623060',
    projectId: 'fir-fluter-codelab-4fc8c',
    storageBucket: 'fir-fluter-codelab-4fc8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY8NDzfv1Srjxg4s1nM0dAac2FMnpMw4Q',
    appId: '1:388247623060:ios:28033c5c10c0d38a2aab81',
    messagingSenderId: '388247623060',
    projectId: 'fir-fluter-codelab-4fc8c',
    storageBucket: 'fir-fluter-codelab-4fc8c.appspot.com',
    iosClientId: '388247623060-0no6u01bf5rkrf463scc8q4kmei09pau.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY8NDzfv1Srjxg4s1nM0dAac2FMnpMw4Q',
    appId: '1:388247623060:ios:28033c5c10c0d38a2aab81',
    messagingSenderId: '388247623060',
    projectId: 'fir-fluter-codelab-4fc8c',
    storageBucket: 'fir-fluter-codelab-4fc8c.appspot.com',
    iosClientId: '388247623060-0no6u01bf5rkrf463scc8q4kmei09pau.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
